feat: added changes for zsec script to support VMSS features

diff --git a/examples/zsec b/examples/zsec
--- a/examples/zsec
+++ b/examples/zsec
@@ -36,56 +36,61 @@ if [[ "$oper" == "up" ]]; then
     do
         case $REPLY in
             1)
-            echo "Greenfield deployment selected..."
-            echo "${YELLOW}**Caution** These deployments include test workloads and publicly accessible jump hosts and are intended primarily for lab/test environments${RESET}"
-            echo ""
-            deployment=greenfield
+                echo "Greenfield deployment selected..."
+                echo "${YELLOW}**Caution** These deployments include test workloads and publicly accessible jump hosts and are intended primarily for lab/test environments${RESET}"
+                echo ""
+                deployment=greenfield
             break
             ;;
             2)
-            echo "Brownfield deployment selected..."
-            deployment=brownfield
+                echo "Brownfield deployment selected..."
+                deployment=brownfield
             break
             ;;
             *) 
-            echo "${RED}invalid response${RESET}"
+                echo "${RED}invalid response${RESET}"
         esac
     done
 fi
 
 if [[ "$deployment" == "greenfield" ]]; then
     PS3="${CYAN}Select desired deployment type: ${RESET}"
-    dtypes=("Deploy 1 Cloud Connector in a new Resource Group and VNet" "Deploy 1 Cloud Connector in a new Resource Group and VNet w/ Private DNS for ZPA" "Deploy multiple Cloud Connectors w/ Load Balancer in a new Resource Group and VNet" "Deploy multiple Cloud Connectors w/ Load Balancer in a new Resource Group and VNet w/ Private DNS for ZPA" "Deploy a new Resource Group and VNet only - No Cloud Connector" )
+    dtypes=("Deploy 1 Cloud Connector in a new Resource Group and VNet" "Deploy 1 Cloud Connector in a new Resource Group and VNet w/ Private DNS for ZPA" "Deploy multiple Cloud Connectors w/ Load Balancer in a new Resource Group and VNet" "Deploy multiple Cloud Connectors w/ Load Balancer in a new Resource Group and VNet w/ Private DNS for ZPA" "Deploy a new Resource Group and VNet only - No Cloud Connector" "Deploy Virtual Machine Scale Set of Cloud Connectors w/ Load Balancer in a new Resource Group and VNet" )
     select greenfield_type in "${dtypes[@]}"
     do
         case $REPLY in
             1)
-            echo "Deployment type base_1cc selected..."
-            dtype=base_1cc
-            break
-            ;;
+                echo "Deployment type base_1cc selected..."
+                dtype=base_1cc
+                break
+                ;;
             2)
-            echo "Deployment type base_1cc_zpa selected..."
-            dtype=base_1cc_zpa
-            break
-            ;;
+                echo "Deployment type base_1cc_zpa selected..."
+                dtype=base_1cc_zpa
+                break
+                ;;
             3)
-            echo "Deployment type base_cc_lb selected..."
-            dtype=base_cc_lb
-            break
-            ;;
+                echo "Deployment type base_cc_lb selected..."
+                dtype=base_cc_lb
+                break
+                ;;
             4)
-            echo "Deployment type base_cc_lb_zpa selected..."
-            dtype=base_cc_lb_zpa
-            break
-            ;;
+                echo "Deployment type base_cc_lb_zpa selected..."
+                dtype=base_cc_lb_zpa
+                break
+                ;;
             5)
-            echo "Deployment type base selected..."
-            dtype=base
-            break
-            ;;
+                echo "Deployment type base selected..."
+                dtype=base
+                break
+                ;;
+            6)
+                echo "Deployment type base_cc_vmss selected..."
+                dtype=base_cc_vmss
+                break
+                ;;
             *) 
-            echo "${RED}invalid response${RESET}"
+                echo "${RED}invalid response${RESET}"
         esac
     done
 elif [[ "$deployment" == "brownfield" ]]; then
@@ -95,12 +100,12 @@ elif [[ "$deployment" == "brownfield" ]]; then
     do
         case $REPLY in
             1)
-            echo "Deployment type cc_lb selected..."
-            dtype=cc_lb
-            break
-            ;;
+                echo "Deployment type cc_lb selected..."
+                dtype=cc_lb
+                break
+                ;;
             *) 
-            echo "${RED}invalid response${RESET}"
+                echo "${RED}invalid response${RESET}"
         esac
     done
 else
@@ -744,6 +749,187 @@ first_run="yes"
             * ) echo "${RED}Invalid response. Please enter yes or no${RESET}";;
             esac
         done
+        # VMSS specific inputs
+        if [[ $dtype == *"vmss"* ]]; then
+        #########################################
+        # Min/Desired/Max VMSS Configuration
+        #########################################
+        # min count
+            vmss_min_default=2
+            read -r -p "${CYAN}Enter the minimum amount of Cloud Connectors in VMSS? [Default=$vmss_min_default]: ${RESET}" vmss_min_input
+            vmss_min=${vmss_min_input:-$vmss_min_default}
+            if (( $vmss_min < 1 || $vmss_min > 20 )); then
+                echo "${RED}invalid vmss_min value. Must be a number between 1 and 20${RESET}"
+                echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                exit 1
+            fi
+
+            # desired count
+            vmss_desired_default=2
+            read -r -p "${CYAN}Enter the desired amount of Cloud Connectors in VMSS? [Default=$vmss_desired_default]: ${RESET}" vmss_desired_input
+            vmss_desired=${vmss_desired_input:-$vmss_desired_default}
+            if (( $vmss_desired < 1 || $vmss_desired > 20 )); then
+                echo "${RED}invalid vmss_desired value. Must be a number between 1 and 20${RESET}"
+                echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                exit 1
+            fi
+
+            # max count
+            vmss_max_default=5
+            read -r -p "${CYAN}Enter the maximum amount of Cloud Connectors in VMSS? [Default=$vmss_max_default]: ${RESET}" vmss_max_input
+            vmss_max=${vmss_max_input:-$vmss_max_default}
+            if (( $vmss_max < 1 || $vmss_max > 20 )); then
+                echo "${RED}invalid vmss_max value. Must be a number between 1 and 20${RESET}"
+                echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                exit 1
+            fi
+
+            # validate values
+            if (( $vmss_desired < $vmss_min || $vmss_desired > $vmss_max )); then
+                echo "${RED}invalid vmss_desired value. Must be a number between vmss_min and vmss_max${RESET}"
+                echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                exit 1
+            fi
+
+            echo "${dtype} will deploy VMSS with min: ${vmss_min} desired: ${vmss_desired} max: ${vmss_max} Cloud Connectors in ${azure_location}"
+            echo "export TF_VAR_vmss_min_ccs=${vmss_min}" >> .zsecrc
+            echo "export TF_VAR_vmss_desired_ccs=${vmss_desired}" >> .zsecrc
+            echo "export TF_VAR_vmss_max_ccs=${vmss_max}" >> .zsecrc
+
+            #########################################
+            # Scheduled Scaling Configuration
+            #########################################
+            # enable/disable scheduled scaling
+            while true; do
+                read -r -p "${CYAN}Do you want to enable scheduled scaling on the VMSS? [yes/no]: ${RESET}" response
+                case $response in 
+                    no|n ) 
+                        echo "Skipping scheduled scaling configuration."
+                        break
+                        ;;
+                    yes|y )
+                        # min count
+                        vmss_sched_min_default=2
+                        read -r -p "${CYAN}Enter the minimum amount of scheduled Cloud Connectors in VMSS? [Default=$vmss_sched_min_default]: ${RESET}" vmss_sched_min_input
+                        vmss_sched_min=${vmss_sched_min_input:-$vmss_sched_min_default}
+                        if (( $vmss_sched_min < 1 || $vmss_sched_min > 20 )); then
+                            echo "${RED}invalid vmss_sched_min value. Must be a number between 1 and 20${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        elif (( $vmss_sched_min > $vmss_max )); then
+                            echo "${RED}invalid vmss_sched_min value. Must be a number between less than or equal to vmss_max${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        fi
+
+                        # days of the week
+                        days_of_week=()
+                        potential_days_of_week=("Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday "Saturday)
+                        for day in ${potential_days_of_week[@]}; do
+                            while true; do
+                                read -r -p "${CYAN}Apply Scheduled Scaling Policy on ${day}? [yes/no]: ${RESET}" resp
+                                case $resp in 
+                                    no|n ) 
+                                        echo "Not configuring ${day} on Scheduled Scaling configuration."
+                                        break
+                                        ;;
+                                    yes|y )
+                                        echo "Adding ${day} on Scheduled Scaling configuration."
+                                        days_of_week+=($day)
+                                        break
+                                        ;;
+                                    * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
+                                esac
+                            done
+                        done
+                        #format days of week array into list
+                        days_of_week_str="'["
+                        print_str=""
+                        for day in ${days_of_week[@]}; do
+                            days_of_week_str+="\"${day}\", "
+                            print_str+="${day} "
+                        done
+                        days_of_week_str+="]'"
+                        echo "Configuring the following days on the Scheduled Scaling Policy: ${print_str}"
+                        
+                        # start time hour
+                        start_hour_default=9
+                        read -r -p "${CYAN}Enter the start time hour for the scheduled scaling configuration? [Default=$start_hour_default]: ${RESET}" start_hour_input
+                        start_hour=${start_hour_input:-$start_hour_default}
+                        if (( $start_hour < 0 || $start_hour > 23 )); then
+                            echo "${RED}invalid start_hour value. Must be a number between 0 and 23${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        fi
+                        # start time minute
+                        start_min_default=0
+                        read -r -p "${CYAN}Enter the start time min for the scheduled scaling configuration? [Default=$start_min_default]: ${RESET}" start_min_input
+                        start_min=${start_min_input:-$start_min_default}
+                        if (( $start_min < 0 || $start_min > 59 )); then
+                            echo "${RED}invalid start_min value. Must be a number between 0 and 59${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        fi
+                        # end time hour
+                        end_hour_default=17
+                        read -r -p "${CYAN}Enter the end time hour for the scheduled scaling configuration? [Default=$end_hour_default]: ${RESET}" end_hour_input
+                        end_hour=${end_hour_input:-$end_hour_default}
+                        if (( $end_hour < 0 || $end_hour > 23 )); then
+                            echo "${RED}invalid end_hour value. Must be a number between 0 and 23${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        fi
+                        # end time minute
+                        end_min_default=30
+                        read -r -p "${CYAN}Enter the end time min for the scheduled scaling configuration? [Default=$end_min_default]: ${RESET}" end_min_input
+                        end_min=${end_min_input:-$end_min_default}
+                        if (( $end_min < 0 || $end_min > 59 )); then
+                            echo "${RED}invalid end_min value. Must be a number between 0 and 59${RESET}"
+                            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
+                            exit 1
+                        fi
+
+                        echo "export TF_VAR_scheduled_scaling_enabled=true" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_vmss_min_ccs=${vmss_sched_min}" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_days_of_week=${days_of_week_str}" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_start_time_hour=${start_hour}" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_start_time_min=${start_min}" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_end_time_hour=${end_hour}" >> .zsecrc
+                        echo "export TF_VAR_scheduled_scaling_end_time_min=${end_min}" >> .zsecrc
+                        break
+                        ;;
+                    * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
+                esac
+            done
+
+            #########################################
+            # Azure Function Configuration
+            # TODO: Possibly remove this for release
+            #########################################
+            # Azure Function Public URL
+            func_public_url_default="https://github.com/zscaler/terraform-azurerm-cloud-connector-modules/raw/ZTW-2872/examples/base_cc_vmss/zscaler_cc_function_app.zip"
+            read -r -p "${CYAN}Enter the public url to retrieve Zscaler CC Azure Function Zip from? [Default=$func_public_url_default]: ${RESET}" func_public_url_input
+            func_public_url=${func_public_url_input:-$func_public_url_default}
+            echo "export TF_VAR_zscaler_cc_function_public_url=${func_public_url}" >> .zsecrc
+
+            # Azure function to terminate unhealthy instances
+            while true; do
+                read -r -p "${CYAN}Allow Azure Function to terminate unhealthy instnces? [yes/no]: ${RESET}" resp
+                case $resp in 
+                    no|n ) 
+                        echo "Azure Function will not terminate unhealthy instances."
+                        echo "export TF_VAR_terminate_unhealthy_instances=false" >> .zsecrc
+                        break
+                        ;;
+                    yes|y )
+                        echo "Azure Function will terminate unhealthy instances."
+                        echo "export TF_VAR_terminate_unhealthy_instances=true" >> .zsecrc
+                        break
+                        ;;
+                    * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
+                esac
+            done
+        fi
     fi
 fi
 
@@ -770,10 +956,10 @@ fi
 
 if [[ $dtype != "base" ]]; then
     echo "Checking Cloud Connector provisioning info"
-  if [ -z "$TF_VAR_cc_vm_prov_url" ] || [ -z "$TF_VAR_azure_vault_url" ] || [ -z "$TF_VAR_http_probe_port" ] || [ -z "$TF_VAR_cc_instance_size" ] || [ -z "$TF_VAR_ccvm_instance_type" ] || [ -z "$TF_VAR_cc_vm_managed_identity_name" ] || [ -z "$TF_VAR_cc_vm_managed_identity_rg" ]; then
-    echo "${RED}Cloud Connector provisioning info is missing. Remove .zsecrc file and rerun $0 $1${RESET}"
-    exit 1
-  fi
+    if [ -z "$TF_VAR_cc_vm_prov_url" ] || [ -z "$TF_VAR_azure_vault_url" ] || [ -z "$TF_VAR_http_probe_port" ] || [ -z "$TF_VAR_cc_instance_size" ] || [ -z "$TF_VAR_ccvm_instance_type" ] || [ -z "$TF_VAR_cc_vm_managed_identity_name" ] || [ -z "$TF_VAR_cc_vm_managed_identity_rg" ]; then
+        echo "${RED}Cloud Connector provisioning info is missing. Remove .zsecrc file and rerun $0 $1${RESET}"
+        exit 1
+    fi
 fi
 
 
@@ -815,7 +1001,7 @@ elif [[ "$oper" == "destroy" ]]; then
     rm -rf user.key user.crt
     rm -rf systems.json setup-*.tar
     rm -rf **/errorlog.txt
-now=$(date +'%Y-%m-%d-%H_%M_%S')
+    now=$(date +'%Y-%m-%d-%H_%M_%S')
     echo "${GREEN}archiving .zsecrc file to .zsecrc-${now}${RESET}"
     cp .zsecrc .zsecrc-${now}
     rm -rf .zsecrc && rm -rf .zsecrc.bak
